[Step3] 다대다 연관 관계 리팩터링
next-step/jpa pull request #13
Opened 2020-12-18 11:43 UTC by coderhglee

안녕하세요 이학균입니다.

3단계 미션 제출합니다.

리뷰 감사드립니다!!

2020-12-18 14:50 UTC, seogi89 requested changes
피드백을 빠르게 잘 반영해주셨네요 👍 
이전 과제에서 이미 다대다 매핑 테이블을 잘 만들어주셔서 손쉽게 요구사항을 만족 할 수 있었어요.
추가로 고민해볼만한 코멘트 남겨 놓았으니 고민 후 수정해보면 좋을 것 같아요.

2020-12-18 14:50 UTC, seogi89 commented on src/main/java/jpa/domain/LineStation.java
> +public class LineStation extends BaseTime {
이전 단계에서 매핑테이블 역할을 하는 엔티티를 만들어서 손쉽게 거리 정보를 추가 할 수 있었어요.

2020-12-18 14:50 UTC, seogi89 commented on src/main/java/jpa/domain/LineStation.java
> +	private int distance;
추가하신 거리 정보만으로는 어떤 역과의 거리차이인지 알 수 없을 것 같아요.

역과 역 사이에 거리를 알기위해서는 어떤 정보를 추가로 알 수 있어야 할까요?

2020-12-19 08:22 UTC, coderhglee commented
`Location` 엔티티를 `LineStation` 엔티티에 추가하여 거리 및 이전 역 정보를 저장하였습니다. 

감사합니다!

2020-12-20 03:07 UTC, seogi89 requested changes
리뷰가 늦어 죄송합니다.

추가로 몇가지 코멘트 남겨 놓았으니 확인 해주세요.

2020-12-20 03:07 UTC, seogi89 commented on src/main/java/jpa/domain/Location.java
> +public class Location extends BaseTime {
새로운 엔티티를 만들기보다는 기존에 라인스테이션에 이전역 정보를 추가하는 것은 어떻게 생각하시나요?

객체의 응집성을 위해서라면 @embedded를 사용 해보는건 어떤가요?

2020-12-20 03:07 UTC, seogi89 commented on src/main/java/jpa/domain/Location.java
> +	private LineStation previousStation;
Station 이 아닌 LineStation을 선택하신 이유가 궁금하네요  🤔

2020-12-20 03:17 UTC, coderhglee commented on src/main/java/jpa/domain/Location.java
> +	private LineStation previousStation;
이전역, 거리에 대한 엔티티를 분리하면서 이전역이 `Line` 정보도 가져야 할 것 같아 LineStation을 선택하였는데.. 위에 말씀해주신 Embedded를 활용하면 해결될꺼같습니다 ㅎㅎ

2020-12-20 03:17 UTC, coderhglee commented on src/main/java/jpa/domain/Location.java
> +public class Location extends BaseTime {
감사합니다!!👍

2020-12-20 09:38 UTC, coderhglee commented
`Embedded` 방식으로 추가하여 반영하였습니다.

감사합니다!

2020-12-21 04:31 UTC, seogi89 approved these changes
피드백 반영하신 내용 확인했어요 
JPA 마지막 단계까지 구현 깔끔하게 잘 하셨어요 👍 
저와의 미션은 종료되었지만 앞으로 궁금한점이나 어려운점 있으면 편하게 DM 주세요.

감사합니다.

다음 미션도 화이팅하세요 🔥

2020-12-21 04:31 UTC, merged