[STEP1] 엔티티 매핑
next-step/jpa pull request #14
Opened 2020-12-18 12:16 UTC by hhlyn0328

안녕하세요 JPA 미션 잘 부탁드립니다 :) 
요구사항이 그저 학습테스트를 진행해보라 하셔서 이건 어떻게 동작할까? 
궁금한 이런저런 jpql을 사용해봤는데 너무 과했나 싶기도 하네요 😅 
코멘트 주시면 반영하겠습니다 감사합니다 !

2020-12-19 07:54 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드릴게요

다음 요청 시 머지하도록 하겠습니다.

2020-12-19 07:54 UTC, kyucumber commented on src/main/java/jpa/Application.java
> +@EnableJpaAuditing
JpaAuditing을 통해 중복되는 부분들을 잘 제거해주셨네요 👍

아마 알고 계실 것 같은데 이후 `@LastModifiedBy, @CreatedBy`과 같은 부분이 이후 추가되면 auditorAwareRef도 정의해 구현해주셔야 합니다.

관련해서 자세히 알고계신게 아니라면 한번 학습해보셔도 좋을 것 같아요

2020-12-19 07:54 UTC, kyucumber commented on src/main/java/jpa/domain/BaseEntity.java
> +	@GeneratedValue(strategy = GenerationType.IDENTITY)
```java
public enum GenerationType { 
    TABLE, 
    SEQUENCE, 
    IDENTITY, 
    AUTO
}
```

각각 어떤 케이스에 GenerationType을 적절하게 사용해야 하는지 알아두시면 좋을 것 같아요.

https://gmlwjd9405.github.io/2019/08/12/primary-key-mapping.html

2020-12-19 07:54 UTC, kyucumber commented on src/main/java/jpa/domain/Favorite.java
> +public class Favorite extends BaseEntity{
```suggestion
public class Favorite extends BaseEntity {
```

2020-12-19 07:54 UTC, kyucumber commented on src/main/java/jpa/domain/LineRepository.java
> +	List<Line> findAllByOrderByColorDesc();
query method들을 여러개 잘 테스트 해보셨네요~ 👍 

저도 매번 헷갈려서 항상 찾아보면서 작성합니다 ㅠㅠ

https://www.baeldung.com/spring-data-derived-queries

2020-12-19 07:54 UTC, kyucumber commented on src/test/java/jpa/domain/FavoriteRepositoryTest.java
> +}
미션의 내용과는 별개지만 참고가 되실까봐 내용 첨부합니다.

파일의 끝에 newline이 포함해주시면 좋을 것 같아요!
POSIX 표준에 맞지 않기도 하고 작업 시 newline을 붙이는데 다른 작업자가 붙이지 않는 경우 불필요한 file change가 생기기도 합니다.

저 같은 경우 IntelliJ에서 newline을 자동으로 추가하는 설정을 사용하고 있습니다.

![image](https://user-images.githubusercontent.com/34656258/81493539-030f0d80-92dc-11ea-8129-756ca65b99cc.png)

https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2020-12-19 07:54 UTC, kyucumber commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
JPA를 실무에서 사용하지 않으실수있을 것 같아 혹시나 도움이 되실까봐 아래 코멘트 남겨봅니다.

보통은 ddl-auto를 디폴트로 validate 등으로 선언하고 local profile에서만 create-drop, create 등을 사용합니다.

물론 서비스에 사용하는 계정에 DDL 권한이 포함되어 있지 않겠지만 배포 시 의도치 않게 해당 설정으로 장애가 발생하거나 할 수 있어요.

2020-12-19 07:56 UTC, kyucumber approved these changes
코멘트 남긴 것 중에 따로 반영해야 할 부분이 없을 것 같아 바로 머지하도록 할게요.

2020-12-19 07:56 UTC, merged

2020-12-20 05:23 UTC, hhlyn0328 commented on src/main/java/jpa/Application.java
> +@EnableJpaAuditing
잘 알고 있던 부분은 아니라서 한 번 확인해보겠습니다 
감사합니다  :)

2020-12-20 05:23 UTC, hhlyn0328 commented on src/main/java/jpa/domain/BaseEntity.java
> +	@GeneratedValue(strategy = GenerationType.IDENTITY)
네 감사합니다 :)

2020-12-20 05:23 UTC, hhlyn0328 commented on src/main/java/jpa/domain/LineRepository.java
> +	List<Line> findAllByOrderByColorDesc();
해당링크가 400이 떨어지네요 관련내용 찾아보겠습니다 감사합니다 :)

2020-12-20 05:23 UTC, hhlyn0328 commented on src/test/java/jpa/domain/FavoriteRepositoryTest.java
> +}
네 설정에 추가하면 좋겠네요 ㅠㅠ 감사합니다!

2020-12-20 05:24 UTC, hhlyn0328 commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
넵! 자칫하다가는 DB 날려서 사장님이랑 면담하게 된다고 하셨는데 안바꿨네요 😅 
validate를 사용하도록 하겠습니다