🚀 3단계 - 다대다 연관 관계 리팩터링
next-step/jpa pull request #17
Opened 2020-12-19 01:48 UTC by lsb156

ManyToMany를 OneToMany, ManyToOne으로 푸는것은 이전 Step에 이미 적용이 되어있어 별로 수정할건 없었던거 같습니다.
(김영한님이 절대 ManyToMany는 하지 말라고 하셔서.....)

그리고 거리의 정보를 넣는것을 두가지로 생각해 봤었습니다.
1. 현재의 Line, 현재역과 다음역의 정보를 가지고있는 별도의 테이블을 구성하여 테이터를 밀어넣는다.
    - LineStation의 Line,Station 정보를 이용하여 OneToMany 형태로 내 기준으로 인접되어있는 역들의 거리 정보를 맵핑
2. LineStation으로 만들어진 Entity에 거리정보와 그 거리와 차이나는 역정보를 저장

1번은 인접되어있는 모든 역들이 있어 양방향이나 환승역 그래프 탐색이 가능하다는 장점이 있고 비용적인 단점이 있고
2번은 객체 그래프탐색이 단방향으로만 되어있지만 조회하는 비용적인 면이 적은거 같습니다.
제가 봤을때는 2번을 의도로 하고 냈던 Step이였던거 같은데 혹시 제가 다르게 생각한거라면 지적 부탁드립니다.

2020-12-20 01:46 UTC, kang-hyungu requested changes
상배님 3단계도 구현 잘 하셨어요 👍 
조금만 더 수정해보면 좋을 부분에 코멘트 남겼어요
수정하시고 리뷰 재요청주시면 빠르게 머지 처리할게요

2020-12-20 01:46 UTC, kang-hyungu commented on src/main/java/jpa/domain/Favorite.java
> +import com.sun.istack.NotNull;
javax.validation.constraints 를 사용해야되지 않을까요?

2020-12-20 01:46 UTC, kang-hyungu commented on src/main/java/jpa/domain/Meter.java
> +    private int meter;
인스턴스 변수가 메서드보다 상단에 위치해야 합니다

2020-12-20 01:46 UTC, kang-hyungu commented on src/main/java/jpa/domain/Member.java
>  import org.springframework.util.StringUtils;
다른 엔티티도 스프링 유틸을 사용하는지 확인해보는게 좋겠네요

2020-12-20 01:46 UTC, kang-hyungu commented on src/main/java/jpa/domain/LineStation.java
> +    private Meter distance;
meter 클래스를 추가해야될 필요가 없어보이는데...
int로 처리하고 validation만 음수 못 넣게 해도 되지 않을까요?

2020-12-20 01:46 UTC, kang-hyungu commented on src/main/java/jpa/domain/LineStation.java
> +    @Convert(converter = MeterInteger.class)
1. MetaConverter로 클래스명을 바꾸는게 좋을 것 같습니다
2. converter 대신 Embedded 어노테이션을 추천합니다

2020-12-20 01:46 UTC, kang-hyungu commented on src/main/java/jpa/domain/LineStation.java
> +    private Station distanceTargetStation;
이렇게 보니 distance, distanceTargetStation을 하나로 묶은 클래스를 만드는것도 나쁘지 않겠네요

2020-12-20 01:46 UTC, kang-hyungu commented on src/main/java/jpa/domain/LineStation.java
> +    static class MeterInteger implements AttributeConverter<Meter, Integer> {
jpa를 안쓰게 되는 케이스도 고려해서 컨버터는 외부 클래스로 따로 만드는게 좋겠네요

2020-12-20 01:48 UTC, kang-hyungu commented
1, 2번 두 가지 방법 중에 2번을 적용하셨군요

2020-12-20 18:08 UTC, lsb156 commented
Meter를 사용한 이유는 도메인 관점에서 거리에 대한 단위가 한번에 보였으면 좋겠다고 생각했는데
그렇게 사용함으로써 JPA에 의존적인 코드들이 나와버린거 같네요
Distance에 거리와 대상 역 정보를 넣어서 Embed 형태로 구현하였습니다.
혹시 추가로 변경될 곳 있으면 언급 부탁드립니다.

2020-12-21 00:46 UTC, kang-hyungu approved these changes
상배님 반영하신 내용 확인했어요
jpa 마지막 단계까지 구현 깔끔하게 잘 하셨어요 👍 
pr은 머지 처리하겠습니다. 수고하셨습니다!

2020-12-21 00:46 UTC, kang-hyungu commented on src/main/java/jpa/domain/Distance.java
> +    public Distance() {
```suggestion
    protected Distance() {
```

2020-12-21 00:46 UTC, kang-hyungu commented on src/main/java/jpa/domain/Distance.java
> +    public Distance(Integer distanceMeter, Station distanceTargetStation) {
```suggestion
    public Distance(int distanceMeter, Station distanceTargetStation) {
```

2020-12-21 00:46 UTC, kang-hyungu commented on src/main/java/jpa/domain/Member.java
> +import com.sun.istack.NotNull;
아직 sun 코드가 남아있네요
다른 클래스도 같이 점검해보아요

2020-12-21 00:47 UTC, merged