[Step3] 리뷰 요청 드립니다 :)
next-step/jpa pull request #27
Opened 2020-12-19 16:08 UTC by leeyohan93

안녕하세요 시홍님 :) 

벌써 JPA 마지막 단계 입니다.. 아직 배울 것이 한참 남았는데 .. 😢 

이번 단계에서는 제 나름대로 요구사항을 만족하면서 이것 저것을 추가해 보았습니다 ! :) 

요구사항을 잘 이해하고 추가된 것인지, 과한 설계가 아닌지 등 이번에도 시홍님의 좋은 피드백 부탁드립니다 😄 

그리고 저번 flush에 대한 피드백 남겨주셨었는데 많은 도움이 되었습니다! 답글 달아놓았으니 한번 봐주셔도 좋을 것 같아요 👍 👍 

감사합니다 ! 🙇 

- [flush 피드백](https://github.com/next-step/jwp-jpa/pull/7#discussion_r545801952)

2020-12-20 07:36 UTC, hongsii requested changes
이전 단계에 미리 구조를 잡아 두셔서 큰 변경없이 요구사항을 반영하셨네요! 👍 
간단한 피드백 남겼으니 확인하셔서 반영해주세요!

2020-12-20 07:36 UTC, hongsii commented on src/main/java/jpa/converter/DistanceConverter.java
> +public class DistanceConverter implements AttributeConverter<Distance, Long> {
`AttributeConverter` 활용 👍 
`@Embedded` 를 사용해볼 수도 있었을텐데 `AttributeConverter` 를 선택하신 이유가 궁금합니다 :)

2020-12-20 07:36 UTC, hongsii commented on src/main/java/jpa/domain/Distance.java
> +public class Distance {
VO 👍

2020-12-20 07:36 UTC, hongsii commented on src/main/java/jpa/domain/LineStation.java
> +    private Distance distance;
> 노선에 역을 추가할 때는 이전 역과 얼마나 차이가 나는지 길이(distance)를 알고 있어야 한다.

`station`, `distance` 만 알면 어떤 역과 얼마나 차이가 나는지를 알 수 있을까요?

2020-12-20 07:36 UTC, hongsii commented on src/main/java/jpa/domain/Line.java
> +        return this;
메서드에서 결과를 반환한다면 이 메서드를 사용할 때 무엇을, 왜 반환하는지 확인을 해야 합니다.
호출한 곳에서 이 인스턴스가 필요하더라도 메서드를 호출하려면 이미 인스턴스를 알기 때문에 이 반환값은 사용되지 않을 가능성이 높습니다.
빌더 패턴과 같은 곳에서 체이닝 용도로 사용할 이유가 아니라면 `this` 와 같은 반환문은 없애는게 불필요한 노이즈를 줄일 수 있습니다.

2020-12-20 08:16 UTC, leeyohan93 commented on src/main/java/jpa/domain/Line.java
> +        return this;
피드백 감사합니다 ! :) 
수정해서 반영하도록 하겠습니다 ! 👍 👍

2020-12-20 08:19 UTC, leeyohan93 commented on src/main/java/jpa/domain/LineStation.java
> +    private Distance distance;
이전 역에 대한 정보를 추가해서 반영해보도록 하겠습니다 ! :) 

피드백을 받고 길이(`distance`)에 대한 정보 또한 두 역을 비교해서 도출해 낼 수 있었다면 하고 생각해보았는데 
현재 요구사항에는 없는 부분이니 어떤 역과 얼마나 차이나는 지에 대해 집중하도록 해보겠습니다 ! 😄 

피드백 감사드립니다 :)

2020-12-20 08:22 UTC, leeyohan93 commented on src/main/java/jpa/converter/DistanceConverter.java
> +public class DistanceConverter implements AttributeConverter<Distance, Long> {
요구사항에 대해 데이터베이스에 저장되는 길이에 대한 정보를 `1000m` , `1km` 등과 같이 여러 타입으로 생각해 보았는데,

조금 과한 것이 아닌지, 오히려 이러한 부분이 복잡도를 올리는게 아닌가 해서 미터 단위로 통일하여 구현하였습니다 ㅎㅎ.. 

그 결과 오히려 `AttributeConverter` 보다는 `@Embeded`를 사용한 활용이 더욱 적합한 사용처럼 보이네요 👍 

피드백 감사드립니다 !

2020-12-20 16:00 UTC, leeyohan93 commented
안녕하세요 시홍님 ! :)

이번 피드백을 반영하면서 `distance` 에 대한 아쉬움이 조금 들었습니다. 

예를 들어 길이가 두 지하철 역을 비교해서 반환되는 값이 라면 `LineStation` 의 생성자의 파라미터가 줄어 들 수 있었을 텐데 하구요 ㅎㅎ.. 

네개의 생성자를 보니 마음이 너무 아프지만 값 객체로 묶는 것보다는 추후에 요구사항으로 푸는 것이 더 적절하다고 판단 하였습니다 :)

제가 놓친 좀 더 좋은 방법이 있었을까요? 🤔 


그리고 `AttributeConverter`에 물어보신 답을 댓글로 달아 놓았는데 이 부분에 대해서 시홍님 의견이 궁금합니다 !

지하철역간의 거리를 데이터베이스에 저장할때 어느 쪽으로 데이터베이스의 값을 지정하시는 것을 더 선호하시나요 ? 

- 거리의 단위까지 함께 기록하는 `1000m`또는 `1km` 같은 방식으로 지정하는 방식
- 회사 데이터베이스의 약속?으로 '길이는 미터 단위이다' 라고 정의하고 숫자 `1000`만을 이용하는 방식 

이번 피드백도 정말 감사드립니다 👍 👍 👍

2020-12-21 15:45 UTC, hongsii approved these changes
피드백 반영을 잘 해주셨네요! 👍 
크게 피드백 드릴 부분이 없어 머지하도록 할게요. 혹시나 추가로 궁금하신 점이 있다면 편하게 DM주세요 :)
미션 진행하시느라 고생많으셨습니다.
남은 미션도 화이팅하셔서 완주하시길 바랍니다! 🙏

2020-12-21 15:45 UTC, hongsii commented on src/main/java/jpa/converter/DistanceConverter.java
> +public class DistanceConverter implements AttributeConverter<Distance, Long> {
> 지하철역간의 거리를 데이터베이스에 저장할때 어느 쪽으로 데이터베이스의 값을 지정하시는 것을 더 선호하시나요 ?

어떠한 용도로 사용하냐에 따라 저장하는 방식은 달라질 수 있지만, 지금과 같은 요구사항이라면 최대한 간단하고 직관적으로 데이터를 저장할 수 있도록 미리 암묵적인 단위를 정해두고 사용하는 방식을 선택할 것 같네요 ㅎㅎ

2020-12-21 15:46 UTC, merged