Step3 : 다대다 연관 관계 리팩터링
next-step/jpa pull request #83
Opened 2020-12-27 15:23 UTC by nawhew

지난번 머지 때 남겨주신 피드백과 distance를 위해서 구간 엔티티를 추가하였습니다.
이번에도 코드리뷰 잘 부탁드립니다 :)

2020-12-28 12:16 UTC, hongsii requested changes
3단계 요구사항 구현을 잘 해주셨네요! 👍 
몇 가지 피드백 남겼으니 확인하셔서 반영해주세요!

2020-12-28 12:16 UTC, hongsii commented on src/main/java/jpa/domain/Station.java
> +    private List<Section> downSections = new ArrayList<>();
연관관계가 많아질수록 고려해야할 사항이 많아지기 때문에 항상 양방향 관계를 맺을 필요는 없습니다!
가능하면 단방향으로 외래키를 가진 쪽에 최소한의 연관관계만 맺도록 하는 것이 좋습니다.

2020-12-28 12:16 UTC, hongsii commented on src/main/java/jpa/domain/SectionRepository.java
> +public interface SectionRepository extends JpaRepository<Section, Long> {
엔티티는 반드시 하나의 Repository를 가질 필요는 없습니다. 보통은 연관 관계를 맺은 엔티티를 통해서 핸들링이 되도록 구현합니다.
연관 관계를 맺은 엔티티를 통해 저장하고 핸들링되도록 바꿔보면 어떨까요?

2020-12-28 12:16 UTC, hongsii commented on src/main/java/jpa/domain/Member.java
> +    @OneToMany(mappedBy = "member")
멤버가 삭제되면 favorite은 어떻게 되야 할까요?
연관관계 설정 시 `cascade` 옵션도 고려해보면 좋을 것 같아요 :)

2020-12-28 12:16 UTC, hongsii commented on src/main/java/jpa/domain/Section.java
> +public class Section extends JpaAuditingDate {
연결 엔티티 👍

2020-12-28 12:16 UTC, hongsii commented on src/main/java/jpa/domain/Section.java
> +    public void setDistance(int distance) {
setter는 객체의 상태를 변경할 수 있게 만들어 객체의 캡슐화를 쉽게 깨트릴 수 있습니다.
반드시 필요한 것이 아니라면 최대한 생성을 지양하는 것이 좋습니다.

2020-12-28 12:16 UTC, hongsii requested changes
3단계 요구사항 구현을 잘 해주셨네요! 👍 
몇 가지 피드백 남겼으니 확인하셔서 반영해주세요!

2020-12-28 14:06 UTC, nawhew commented on src/main/java/jpa/domain/Station.java
> +    private List<Section> downSections = new ArrayList<>();
Station쪽이 너무 지저분해지기도 하고 관리가 어려워 질 것 같아서 하면서도 이상했습니다!
몇가지 연관관계는 단방향으로 변경하였습니다

2020-12-28 16:58 UTC, nawhew commented on src/main/java/jpa/domain/SectionRepository.java
> +public interface SectionRepository extends JpaRepository<Section, Long> {
SectionRepository를 삭제하고, Line과의 의존 관계 설정에 cascade를 추가하여
Line에서 Section을 저장하고 핸들링되도록 변경하였습니다.

2020-12-28 17:13 UTC, nawhew commented on src/main/java/jpa/domain/Member.java
> +    @OneToMany(mappedBy = "member")
cascade 옵션을 사용하니 관계도 더 명확해지고, 개발자 입장에서도 편한 것 같습니다.
해당 부분 적용하였습니다 :)

2020-12-28 17:16 UTC, nawhew commented on src/main/java/jpa/domain/Section.java
> +    public void setDistance(int distance) {
넵

2020-12-28 17:17 UTC, nawhew commented
이번 피드백으로 cascade에 대해 공부하게 되어 좋았습니다!
코드리뷰 한번 더 잘 부탁드립니다 :)

2020-12-29 12:11 UTC, hongsii approved these changes
피드백 반영을 잘 해주셨네요 👍 
미션 진행하시느라 고생 많으셨습니다!
남은 미션도 힘내셔서 잘 마무리하시길 바랍니다 🙏

2020-12-29 12:11 UTC, merged